#pragma once

#define MAX_ITERATIONS 1000
#define THRESHOLD      10
#define SCALE_FACTOR   0.9

#define WIDTH  800
#define HEIGHT 600

#define NUM_FRAMES 10

#define DEFAULT_START_MAX_REAL 2
#define DEFAULT_START_MAX_IMG  2
#define DEFAULT_START_MIN_REAL -2
#define DEFAULT_START_MIN_IMG  -2

#define DEFAULT_END_MAX_REAL -1.258
#define DEFAULT_END_MAX_IMG  0.378
#define DEFAULT_END_MIN_REAL -1.258
#define DEFAULT_END_MIN_IMG  0.378
